[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.py", "requirements.txt"]

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
